global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'care-service-backend'
    static_configs:
      - targets: ['care-backend:3000']

  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

